import type { Metadata } from 'next'
import { ArrowUpRight, AtSign, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import { ConsultationForm } from '@/components/consultation-form'
import { PageHero } from '@/components/page-hero'
import { SiteFooter } from '@/components/site-footer'
import { SiteNav } from '@/components/site-nav'
import { company } from '@/lib/site-data'

export const metadata: Metadata = { title: 'Contact', description: 'Book a private consultation with Aurexis Surface Transformations.' }
const contacts = [{ icon: Phone, label: 'Call', value: company.phone, href: company.phoneHref }, { icon: MessageCircle, label: 'WhatsApp', value: 'Start a conversation', href: company.whatsappHref }, { icon: Mail, label: 'Email', value: company.email, href: `mailto:${company.email}` }, { icon: AtSign, label: 'Instagram', value: company.instagram, href: company.instagramHref }]
export default function ContactPage() { return <><SiteNav /><main><PageHero eyebrow="Private Consultation" title="Begin with the surface." line="Tell us what exists, what needs to change and what exceptional looks like to you." image="/images/hero-kitchen.png" imageAlt="Refined kitchen with transformed architectural surfaces" />
<section className="mx-auto max-w-7xl px-6 py-24 md:py-36"><div className="grid gap-16 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-label text-accent">Direct enquiries</p><h2 className="mt-5 font-serif text-4xl font-light md:text-5xl">A conversation, not a quotation.</h2><p className="mt-6 max-w-md text-sm leading-relaxed text-muted-foreground">We respond within one working day. For immediate project enquiries, WhatsApp is the fastest route.</p><div className="mt-10 grid gap-3 sm:grid-cols-2">{contacts.map(({icon: Icon,label,value,href}) => <a key={label} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noopener noreferrer' : undefined} className="glass group rounded-2xl p-5"><Icon className="size-5 text-accent" aria-hidden="true" /><span className="mt-5 block text-label text-muted-foreground">{label}</span><span className="mt-1 flex items-center justify-between gap-2 text-sm">{value}<ArrowUpRight className="size-4 opacity-40 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" aria-hidden="true" /></span></a>)}</div></div><div className="lg:col-span-6 lg:col-start-7"><div className="glass rounded-3xl p-7 md:p-10"><ConsultationForm /></div></div></div>
<div className="mt-24 grid gap-6 md:grid-cols-2">{company.offices.map(office => <a key={office.city} href={office.mapHref} target="_blank" rel="noopener noreferrer" className="group relative min-h-72 overflow-hidden rounded-3xl bg-primary p-8 text-primary-foreground"><MapPin className="size-6 text-accent" aria-hidden="true" /><p className="mt-20 text-label text-primary-foreground/50">Studio</p><h2 className="mt-2 font-serif text-3xl font-light">{office.city}</h2><p className="mt-3 text-sm text-primary-foreground/60">{office.lines.join(', ')}</p><ArrowUpRight className="absolute right-8 top-8 size-5 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" aria-hidden="true" /></a>)}</div></section>
</main><SiteFooter /></> }
