import type { Metadata } from 'next'
import { CtaBand } from '@/components/cta-band'
import { PageHero } from '@/components/page-hero'
import { SiteFooter } from '@/components/site-footer'
import { SiteNav } from '@/components/site-nav'

export const metadata: Metadata = { title: 'Frequently Asked Questions', description: 'Answers about Aurexis materials, installation, care and assurance.' }
const groups = [
  { title: 'Working with Aurexis', items: [['What does Aurexis transform?', 'We work across built environments, architectural glass, visual communication and mobility—from cabinetry and privacy film to fleet graphics and vehicle protection.'], ['Do you work outside Cape Town?', 'Yes. We deliver across Southern Africa from Cape Town and Victoria Falls, subject to project scope and site requirements.'], ['How does a project begin?', 'With a consultation and site assessment. We then specify material, prepare samples and provide a clear scope before production.']] },
  { title: 'Materials & installation', items: [['Is resurfacing durable?', 'Yes, when the substrate, material and installation system are correctly matched. We specify commercial or automotive-grade films for their intended use.'], ['Will installation disrupt the space?', 'Usually far less than replacement. Many surfaces can be transformed in place, reducing demolition, noise, dust and closure time.'], ['Can I see samples first?', 'Yes. Physical samples and, where useful, a site mock-up are part of our specification process.']] },
  { title: 'Care & assurance', items: [['How do I care for the finish?', 'Use soft cloths and approved neutral cleaners. Your handover includes care guidance for the exact material installed.'], ['How long is the warranty?', 'It depends on material, application and exposure. Applicable terms are documented in your project handover; some systems are backed for up to ten years.'], ['How do I make a claim?', 'Contact us with your project details, installation date and photographs. We will assess the issue and arrange an inspection when required.']] },
]
export default function FaqPage() { return <><SiteNav /><main><PageHero eyebrow="Information" title="Clear answers. No fine print." line="A considered guide to the way we specify, install and support every surface." compact />
<section className="mx-auto max-w-5xl px-6 py-24 md:py-36">{groups.map(group => <section key={group.title} className="border-b border-border py-14 first:pt-0"><div className="grid gap-8 md:grid-cols-12"><h2 className="font-serif text-3xl font-light md:col-span-4">{group.title}</h2><div className="md:col-span-8">{group.items.map(([question,answer]) => <details key={question} className="group border-t border-border py-6 first:border-t-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-medium"><span>{question}</span><span className="text-2xl font-light text-accent transition-transform group-open:rotate-45" aria-hidden="true">+</span></summary><p className="max-w-2xl pt-5 text-sm leading-relaxed text-muted-foreground">{answer}</p></details>)}</div></div></section>)}</section><CtaBand title="Still considering the details?" line="Bring us the surface, constraint or ambition. We will help define the right system." /></main><SiteFooter /></> }
